image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
    name: Website
    description: Preview of Website
  - port: 5900
    onOpen: ignore
    visibility: public
    name: VNC
    description: VNC Server
  - port: 6080
    onOpen: open-browser
    visibility: public
    name: VNC
    description: VNC Viewer

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/configure/workspaces/tasks/
tasks:
  - init: npm install
    command: npx cypress open
    name: Install

# find extensions https://open-vsx.org/
vscode:
  extensions:
    - usernamehw.errorlens
    - dsznajder.es7-react-js-snippets
    - oderwat.indent-rainbow
    - dbaeumer.vscode-eslint
    - standard.vscode-standard
